#!/usr/bin/env ts-node
/**
 * Simple smoke test for the AI README MCP utilities.
 *
 * Usage:
 *   npm run smoke
 *
 * This script verifies that guidance collection and AI_README updates operate
 * against the local workspace without needing to launch the MCP transport.
 */

import path from "node:path";
import { fileURLToPath } from "node:url";
import { handleGuidance, handleUpdate } from "../src/guidance.js";
import { GuidanceRequest, UpdateRequest } from "../src/types.js";

async function run() {
  const repoRoot = path.resolve(process.cwd());
  const sampleScope = path.join(repoRoot, "sample");
  const demoDir = path.join(repoRoot, ".tmp-smoke");

  console.log("== Smoke Test: AI README MCP ==");
  console.log(`Repository root: ${repoRoot}`);
  console.log("");

  const guidanceRequest: GuidanceRequest = {
    repositoryRoot: repoRoot,
    changedPaths: ["sample/AI_README.md"],
    raw: false
  };

  const guidance = await handleGuidance(guidanceRequest);

  console.log("== Guidance Summary ==");
  console.log(`Matched scopes: ${guidance.scopes.length}`);
  console.log(guidance.aggregatedGuidance);
  console.log("");

  const updateRequest: UpdateRequest = {
    targetDir: demoDir,
    section: "Smoke Test Section",
    body: "This entry was generated by the smoke test.",
    headline: "AI README: Smoke Test",
    changeSummary: "Documented smoke test execution."
  };

  const updateResult = await handleUpdate(updateRequest);

  console.log("== Update Result ==");
  console.log(JSON.stringify(updateResult, null, 2));
  console.log("");

  console.log(`Smoke test complete. Check ${updateResult.filePath} for output.`);
}

run().catch((error) => {
  console.error("Smoke test failed:", error);
  process.exitCode = 1;
});